# Generated by Django 2.2rc1 on 2019-04-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contactphone',
            new_name='contactPhone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
