# Generated by Django 2.2 on 2019-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20190408_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='databaseID',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
